name: Build EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Compile CPP
        run: g++ definitivo.cpp -o programa.exe

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: programa
          path: programa.exe
